In [1]:
import numpy as np

# 1-Create Numpy Array A of size 4 x 5 and Numpy Array B of Size 5 x 4.

In [4]:
a=np.array([[1,2,3,4,5],[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9]])
print(a)

[[1 2 3 4 5]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [7]:
b=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4],[5,5,5,5]])
print(b)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]


## Generate a matrix C as a resultent of multiplication of A and B{using loop}.

In [14]:
c=np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]])
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            c[i][j] += a[i][k] * b[k][j]
print(c)

[[ 55  55  55  55]
 [ 85  85  85  85]
 [100 100 100 100]
 [115 115 115 115]]


## 1 Generate a matrix C as a resultent of multiplication of A and B{use library method}.

In [16]:
c=np.matmul(a,b)
c

array([[ 55,  55,  55,  55],
       [ 85,  85,  85,  85],
       [100, 100, 100, 100],
       [115, 115, 115, 115]])

# Create a Numpy array A of size 5 x 5 value ranging 0 t0 10.

In [17]:
a=np.random.randint(0,10,size=(5,5))
a

array([[0, 5, 7, 4, 6],
       [8, 1, 5, 0, 2],
       [9, 8, 4, 9, 1],
       [1, 1, 7, 5, 3],
       [1, 5, 5, 5, 5]])

## Find the transpose of A. Name it at.

In [18]:
at=np.transpose(a)
at

array([[0, 8, 9, 1, 1],
       [5, 1, 8, 1, 5],
       [7, 5, 4, 7, 5],
       [4, 0, 9, 5, 5],
       [6, 2, 1, 3, 5]])

## Find a x at

In [19]:
B=np.dot(a,at)
B

array([[126,  52, 110,  92, 110],
       [ 52,  94, 102,  50,  48],
       [110, 102, 243,  93, 119],
       [ 92,  50,  93,  85,  81],
       [110,  48, 119,  81, 101]])

# Create a Numpy array A of size 4 x 4.

In [20]:
a=np.random.randint(0,10,size=(4,4))
a

array([[0, 8, 3, 1],
       [1, 9, 1, 9],
       [2, 6, 9, 0],
       [3, 2, 8, 8]])

## Find the Determinent of a

In [21]:
ad=np.linalg.det(a)
ad

-436.9999999999999

## Find the inverse of a.

In [22]:
ai=np.linalg.inv(a)
ai

array([[-1.99084668,  1.05720824,  1.38215103, -0.94050343],
       [-0.09839817,  0.13501144,  0.14187643, -0.1395881 ],
       [ 0.50800915, -0.32494279, -0.29061785,  0.3020595 ],
       [ 0.26315789, -0.10526316, -0.26315789,  0.21052632]])

#  Create two Numpy array A and B of Size 6 x 6.

In [25]:
a=np.random.randint(0,30,size=(6,6))
a

array([[ 3, 22,  5, 23, 27, 10],
       [16, 17, 24, 12, 18, 16],
       [27, 23,  6, 18,  7, 21],
       [12, 23, 12, 25, 27, 25],
       [13, 16, 16, 23,  2,  2],
       [ 5, 21,  1, 23,  7, 18]])

In [26]:
b=np.random.randint(0,30,size=(6,6))
b

array([[13, 28, 19,  3, 19,  3],
       [20, 19, 20, 21, 26, 21],
       [ 1, 10, 10, 19, 20, 18],
       [17, 22,  0, 15, 27, 27],
       [29, 24,  3, 26,  5, 13],
       [ 4, 15,  0, 23, 17,  3]])

## Find the elsment wise multiplication of a,b and store it in c.

In [28]:
c=a*b
c

array([[ 39, 616,  95,  69, 513,  30],
       [320, 323, 480, 252, 468, 336],
       [ 27, 230,  60, 342, 140, 378],
       [204, 506,   0, 375, 729, 675],
       [377, 384,  48, 598,  10,  26],
       [ 20, 315,   0, 529, 119,  54]])

## Find the inverse of c.

In [29]:
ci=np.linalg.inv(c)
ci

array([[-5.47335857e-04,  7.63542066e-05, -1.62216170e-03,
         9.85804572e-04,  2.34742894e-03, -2.26868621e-03],
       [ 2.50406712e-03, -1.04911891e-03,  3.42624439e-03,
        -1.35630281e-03,  1.25241747e-03, -2.49623883e-03],
       [ 2.44812093e-04,  1.95279787e-03,  1.34559996e-03,
        -1.73288831e-03, -8.61169278e-04,  3.69792173e-04],
       [-1.26555243e-03,  4.72829986e-04, -1.35632604e-03,
         3.56667654e-04, -5.28153129e-04,  3.05126402e-03],
       [-8.88128675e-04,  8.53345044e-04, -4.24845681e-03,
         1.82477467e-03, -1.46512476e-03,  2.81864700e-03],
       [-4.94421953e-05, -4.20921290e-04,  3.26368682e-03,
         3.13688609e-05,  2.27458716e-04, -2.18238346e-03]])